spring:
 application:
  name: zuul-server
server:
  port: 9401
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:9101/eureka/,http://peer2:9102/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: discovery-service
    api-b:
      path: /api-b/**
      serviceId: feign-server

