spring:
 application:
  name: zuul-server
server:
  port: 9150
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9100/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: discovery-service
    api-b:
      path: /api-b/**
      serviceId: feign-server

