spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: http://git.oschina.net/didispace/SpringBoot-Learning/
          searchPaths: Chapter9-1-4/config-repo
          username: username
          password: password
  profiles:
    active: native

  rabbitmq:
    host: chuchen
    port: 5672
    username: chuchen
    password: chuchen

server:
  port: 9501

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:9101/eureka/,http://peer2:9102/eureka/